/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcoin_wallet.java;

import mixin.java.sdk.MixinHttpUtil;
import mixin.java.sdk.MixinAPI;
import java.security.PrivateKey;
import java.security.interfaces.RSAPrivateKey;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;

public class App {

    public static final String EXIN_BOT        = "61103d28-3ac2-44a2-ae34-bd956070dab1";
    public static final String BTC_ASSET_ID    = "c6d0c728-2624-429b-8e0d-d9d19b6592fa";
    public static final String EOS_ASSET_ID    = "6cfe566e-4aad-470b-8c9a-2fd35b49c68d";
    public static final String USDT_ASSET_ID   = "815b0b1a-2764-3736-8faa-42d694fa620a";
    public static final String BTC_WALLET_ADDR = "14T129GTbXXPGXXvZzVaNLRFPeHXD1C25C";

    public static void main(String[] args) {
        MixinAPI mixinApi = new MixinAPI(Config.CLIENT_ID, Config.CLIENT_SECRET,
                                         Config.PIN, Config.SESSION_ID, Config.PIN_TOKEN,
                                         Config.RSA_PRIVATE_KEY);
        JsonArray assets = mixinApi.getAssets();
        assets.forEach((element) ->  {
           JsonObject jsonObj = element.getAsJsonObject();
           System.out.println(jsonObj.get("asset_id").getAsString() + " " +
                              jsonObj.get("symbol").getAsString() + " " +
                              jsonObj.get("balance").getAsString() );
        });
        JsonObject asset = mixinApi.getAsset(BTC_ASSET_ID);
        System.out.println(asset);
    }
}
